//! Build-time info surfaced by `--version`.

// reason: `built.rs` is auto-generated by the `built` crate at build time;
// we cannot edit it, so we silence pedantic lints on the included module.
#[allow(clippy::needless_raw_string_hashes, clippy::doc_markdown, dead_code)]
pub(crate) mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Format the version banner shown by `--version`.
#[must_use]
pub fn version_string() -> String {
    let sha = built_info::GIT_COMMIT_HASH.unwrap_or("unknown");
    let dirty = built_info::GIT_DIRTY.unwrap_or(false);
    let suffix = if dirty { "-dirty" } else { "" };
    format!(
        "tayf {pkg} (sha {sha}{suffix}, rustc {rustc})",
        pkg = built_info::PKG_VERSION,
        rustc = built_info::RUSTC_VERSION,
    )
}
